import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:cricket_scoring_engine/cricket_scoring_engine.dart';
import '../../core/services/scorecard_pdf_service.dart';
import '../profile/profile_notifier.dart';
import '../../core/theme.dart';

class PdfPreviewScreen extends ConsumerWidget {
  final MatchState matchState;

  const PdfPreviewScreen({
    super.key,
    required this.matchState,
  });

  void _shareResultText(BuildContext context) {
    final res = matchState.result;
    final inn1 = matchState.innings.isNotEmpty ? matchState.innings[0] : null;
    final inn2 = matchState.innings.length > 1 ? matchState.innings[1] : null;

    final resultText = StringBuffer();
    resultText.writeln('Match Result Summary');
    resultText.writeln('${matchState.teamA.name} vs ${matchState.teamB.name}');
    if (res != null) {
      resultText.writeln('\nWinner: ${res.resultString}');
    }
    if (inn1 != null) {
      resultText.writeln(
          '1st Innings: ${inn1.totalRuns}/${inn1.totalWickets} (${inn1.oversFormatted} ov)${inn1.completionReason == 'All Out' ? ' All Out' : ''}');
    }
    if (inn2 != null) {
      resultText.writeln(
          '2nd Innings: ${inn2.totalRuns}/${inn2.totalWickets} (${inn2.oversFormatted} ov)${inn2.completionReason == 'All Out' ? ' All Out' : ''}');
    }
    resultText.writeln('\nGenerated by TurfScore');

    Share.share(resultText.toString(),
        subject:
            '${matchState.teamA.name} vs ${matchState.teamB.name} Scorecard');
  }

  void _sharePdfFile(BuildContext context) async {
    final file = await ScorecardPdfService.savePdfLocally(matchState);
    await Share.shareXFiles(
      [XFile(file.path)],
      text:
          '${matchState.teamA.name} vs ${matchState.teamB.name} Match Scorecard PDF',
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final profile = ref.watch(profileNotifierProvider);
    final footerInfo = profile.includeProfileInPdf
        ? 'Scored by ${profile.userName} • Jersey No. ${profile.jerseyNumberDisplay}'
        : null;

    return Scaffold(
      appBar: AppBar(
        title: Text(
            '${matchState.teamA.shortName} vs ${matchState.teamB.shortName} PDF'),
        actions: [
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Share PDF File',
            onPressed: () => _sharePdfFile(context),
          ),
          IconButton(
            icon: const Icon(Icons.text_snippet),
            tooltip: 'Share Result Text',
            onPressed: () => _shareResultText(context),
          ),
        ],
      ),
      body: PdfPreview(
        build: (format) => ScorecardPdfService.generatePdf(matchState,
            scorerFooterInfo: footerInfo),
        allowPrinting: true,
        allowSharing: true,
        canChangeOrientation: false,
        canChangePageFormat: false,
        pdfFileName:
            '${matchState.teamA.shortName}_vs_${matchState.teamB.shortName}_Scorecard.pdf',
        loadingWidget: const Center(
          child: CircularProgressIndicator(),
        ),
      ),
    );
  }
}
